Testing
FrancoSecchi/Tp-2-Algoritmos-Costa pull request #11
Opened 2021-03-01 23:12 UTC by FrancoSecchi

2021-03-02 23:40 UTC, dpalacios95 requested changes
Chicos mejoro muchísimo de lo que era la primera version 👏 😃 
Faltan algunos detalles, pero están re encaminados así que sigan así que falta muy poquito 💃

2021-03-02 23:40 UTC, dpalacios95 commented on custom_bot.py
> +    Returns:
En el caso que la función no retorna nada o no tiene parámetros, no es necesario ponerlo en el docstring, se entiende que no tiene y listo 👍

2021-03-02 23:40 UTC, dpalacios95 commented on custom_bot.py
> +        facebook_api = facebook.connection_api(
Qué les parece si en vez de llamar connection_api() tanto en el if como en el else, simplemente setean un diccionario con las credenciales del usuario si te responde que sí y, sino que sea un diccionario vacío.

credentials = dict()
if user_answer_is_yes(response.lower()):  
credentials = {token=....} # esto dentro del if

facebook_api = facebook.connection_api(credentials)

2021-03-02 23:40 UTC, dpalacios95 commented on custom_bot.py
> +        instagram_api = instagram.connection_instagram(
Lo mismo que con facebook_credentials()

2021-03-02 23:40 UTC, dpalacios95 commented on custom_bot.py
> +def take_name() -> True:
El nombre es super raro, quizá debería llamarse ask_name o ask_user_name

2021-03-02 23:40 UTC, dpalacios95 commented on custom_bot.py
> +    :return:
Agréguenle pre y post condiciones siguiendo la misma convención del resto de las funciones

2021-03-02 23:40 UTC, dpalacios95 commented on custom_bot.py
> +    return True
No entiendo porque siempre retorna True?? Quizá no debería retorna nada, no le encuentro el sentido

2021-03-02 23:40 UTC, dpalacios95 commented on custom_bot.py
> +def facebook_credentials() -> object:
DETALLE: El nombre me hace ruido, quizá debería llamarse connect_to_facebook_api() sin retornar nada, ya que no usan lo que retorna en el resto del código

2021-03-02 23:40 UTC, dpalacios95 commented on custom_bot.py
> +                graph, instagram_api = facebook_credentials(), instagram_credentials()
? No entendi el por qué de hacer esto.. Ademas no usan esas variables en el resto de la función :/

2021-03-02 23:40 UTC, dpalacios95 commented on custom_bot.py
> +        bot = initialize_bot()
Lo mismo que en facebook_credentials() , hagan el chequeo si es necesario lo entrenan, y luego inicializan el bot, de esta forma se evitan repetir código y queda mas prolijo

2021-03-02 23:40 UTC, dpalacios95 commented on apis/facebook.py
> +def validate(number, list_):
mejoren el nombre de la función y de los parámetros, también la descripción de la función

2021-03-02 23:40 UTC, dpalacios95 commented on apis/facebook.py
> +        validate_select(select, albums_id)
validate_select no existe, quizá les falto cambiarle el nombre a la función de arriba 👍

2021-03-02 23:40 UTC, dpalacios95 commented on apis/facebook.py
>              print("The requested file cannot be found")
Mismo que antes, es como que están haciendo un copy-paste de lo que se escribe en el log y lo que printea  en pantalla, quizá puedan hacer la misma lógica que el input?

2021-03-02 23:40 UTC, dpalacios95 commented on apis/facebook.py
> +    name = get_username()
CUIDADO!! get_username() no existe, fíjense si lo perdieron al mercera o si falta importarlo de otro lado

2021-03-02 23:40 UTC, dpalacios95 commented on apis/facebook.py
> +def upload_post(facebook_api: facebook.GraphAPI) -> None or Exception:
Cambien lo que retorna ya no seria None or Exception, sería siempre None

2021-03-02 23:40 UTC, dpalacios95 commented on apis/facebook.py
> +def upload_photo(facebook_api: facebook.GraphAPI) -> None or Exception:
DETALLE: La función siempre retorna None

2021-03-02 23:40 UTC, dpalacios95 commented on apis/facebook.py
> +def if_text_in_info(text, info, post_id, count):
Mmmm... Vale la pena este procedimiento? Veo que lo usan dos veces en la misma función, yo diría que no vale la pena tenerla
Ademas el parametro es post_id y dentro lo llaman posts_id entonces rompe 😬 , metan la lógica en la función post_related que es donde la usan

2021-03-02 23:40 UTC, dpalacios95 commented on apis/facebook.py
> +            if_text_in_info("message", info, posts_id, count)
Aca es donde debería estar las validaciones que tienen en if_text_in_info

2021-03-02 23:40 UTC, dpalacios95 commented on apis/facebook.py
> +def post_related(facebook_api, action, selected) -> None:
Cuidado con usar anotaciones del tipo en algunos lados y en otros no, siempre sigan una sola convención, es todo o nada 😄

2021-03-02 23:40 UTC, dpalacios95 commented on apis/facebook.py
> +def connection_api(user_credentials: dict = {}) -> object:
Cuidado con esto, en Python tanto el diccionario como el set vacío se escribe así {} , en este caso hace confundir y podrían estar esperando un diccionario y sin querer le ponen un set, siempre que definan anotaciones de tipos háganlo de forma clara con los nombres de los objetos: list , set , dict , tuple , int , float, str

2021-03-02 23:40 UTC, dpalacios95 commented on logs.py
> +        except Exception as error:
Fíjense que en el caso que falle no están retornando un string, quizá podrían agregarle un return "Unknown" también acá

2021-03-02 23:40 UTC, dpalacios95 commented on logs.py
Que les parece cambiar el nombre a este archivo? Porque no solo tiene funciones para loggear sino que también tiene helpers o utilidades que usan en otros modulos, o también podrían separar esas funciones en otro archivo .py 
Esto es para que haya una consistencia en el código, y no mezclar manzanas con naranjas 😛

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
> +def is_following_user(api: Client, username: str, client_username: str = '') -> tuple:
Sigo pensando que esta función deberían repensarla porque siempre que tienen muchos ifs anidados estaría demostrando que falta modularizar
No entiendo porque si el usuario soy yo, esta como que me estoy siguiendo a mi mismo, creo que ahi tienen un indicio de que podrían separar de acá 😉

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
> +                 **extra_data) -> tuple:
Qué sentido tiene ponerle **extra_data si la función la llaman una vez y con los parámetros bien definidos? Por qué no agregarle el parámetro de own_feed y de texto?

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
> +                presentation_post += "\t- " + post_data[attribute][0]['full_name'] + " +{} users \n".format(
No entiendo esto, ósea creería que es así:
_Si el post tiene menos o igual a 5 likes, entonces imprimí los nombres de los usuarios,
pero si tiene más solo decime el nombre del primer usuario y la cantidad total de likes_
Lo que me hace pensar porque no listar siempre los nombres o no listarlos nunca y simplemente mostrar la cantidad total de likes 😬 
También por qué uno usa users y el otro usa la info de post_data? Se supone que users sale de post data, si quieren en vez de un for usen un while con un limite, tipo que solo muestre 15 usuarios, piénselo :)

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
> +            presentation_post += indicator_post + title + f'' + "\n"
Ok.. un par de cosas:
1. Hay un metodo de los diccionarios que digamos es más seguro para obtener el valor de una key, el método [get()](https://www.tutorialspoint.com/python3/dictionary_get.htm)
my_dict = {"name": "Fiona", "age": 50}
if my_dict.get("last_name"): 
...
 Esto retorna un string vacío y no saltaría un KeyError de que no existe la key como si lo haría con:
my_dict["last_name"]

2. No usaria el if type(...) == dict sino **isinstance(post_data["caption"], dict)** 

Con lo del punto 1, van a ver que no necesitan el else :)

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
> +        if post_number < 0 or post_number >= max_number:
Esto no tiene sentido, si podes ponerla la condición al while directamente ¿por qué usar una bandera?

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
> +        if not comments['comments'][comment_number]:
Lo mismo de arriba, usen el while con la condición

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
> +        print_write_chatbot("No users with that name were found, please enter a correct name: ")
Por que no hacer el ingreso antes del search, así no tienen un parámetro de más, también eviten el copy-paste seguro tienen una función que hace el print al chatbot

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
>      try:
El try-except es muy grande analicen donde podrían fallar y envuelvan esas partes nada más

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
> +        username = get_username(api)
Esto rompe porque le falta un parámetro a get_username

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
>          if can_get_feed:
Por qué hacer este if inmenso si podes hacer lo contrario:
if not can_get_feed:
print("algo") 
return algo

y el resto de la función sigue como si nada

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
> +            if not is_feed_empty:
Lo mismo que antes, hagan la validación al revés, if is_feed_empty : hacer algo simple + return de algo

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
> +                    if 'comments_disabled' not in feed['items'][number_post]:
No me convence esta validación porque no es algo que vaya a cambiar en el while, entonces me parece que la condición de corte real es want_put_comment, quizá haría algo como esto:
while 'comments_disabled' in feed['items'][number_post] and want_put_comment:
....

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
>      try:
Mismo que antes el try es muy grande

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
>              if can_get_feed:
Por qué no al revés? Se entendería mejor si validan if not can_get_feed , por lo general al validar se hace buscando la condición que esta mal y no al revés. Además de esta forma, el `else` no queda perdido en el código largo del `if`

2021-03-02 23:40 UTC, dpalacios95 commented on apis/facebook.py
> +def validate(number: int, list_: list) -> int:
Mejoren el nombre, que valida? El parámetro list_ que es ? Según el docstring es una lista de albums, pero también lo utilizaron en la función post_related para validar el input de opciones del usuario :/

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
>              while comment_block and want_put_comment:
No entiendo porque usaron `comment_block` como corte si en realidad no cambia dentro? Por qué no hacer la validación de 'comments_disabled'... dentro del while? Se fijaron si funciona igual?

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
> +                    if result['status'] == 'ok':
Detalle / Tip: Siempre que tengo dudas de que iría primero si el if o el try (en este caso) lo leo en "pseudocodigo":
1. Intenta, si el status esta ok, imprimir y escribir al chatbot     -> suena raro
2. Si el status esta ok, intenta imprimir y escribir al chatbot     -> no les parece mejor?

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
> +def get_new_profile_data(profile_data: dict, attributes: dict, new_profile_data: dict, genders: list) -> None:
Me parece que también se puede modularizar un poco mas esta función

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
>                  if api.friendships_destroy(user['pk']):
Por qué dos ifs y no un if .. and ... ?

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
>                  if api.friendships_destroy(user['pk']):
También en esta función el try-except no me convence, creería que lo único que puede fallar es el guardado de los logs, deberían encapsular solo eso y no toda la función :)

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
>      try:
mismo que antes dudo que toda la función pueda fallar, creería que solo falla el logs

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
>  def to_json(python_object) -> dict:
Faltan pre y post condiciones o un docstring

2021-03-02 23:40 UTC, dpalacios95 commented on apis/instagram.py
>      except ClientLoginError as e:
Creeria que este try-except debería encapsular solo la linea 1194, donde setean la variable api = Client(...)

2021-03-03 20:18 UTC, FrancoSecchi commented on custom_bot.py
> +                graph, instagram_api = facebook_credentials(), instagram_credentials()
Tienen que estar, porque cuando el bot ahce el exec del string, va a buscar el graph o el instagram_api

2021-03-03 20:18 UTC, FrancoSecchi commented on custom_bot.py
> +        bot = initialize_bot()
El tema es que para entrenarlo, hay que inicializarlo primero. Y cuando el bot se inicializa, crea la base de datos del bot, entonces la unica forma que pense es esa

2021-03-03 20:18 UTC, FrancoSecchi commented on logs.py
Podria haber funciones que se puedan mandar a utils.py?

2021-03-03 20:18 UTC, FrancoSecchi commented on custom_bot.py
> +    return True
Retorna True para esta linea 
`is_taken_name = take_name()`

2021-03-03 20:27 UTC, FrancoSecchi commented on logs.py
Podriamos poner el get_credentials, get_current_username, el print y el input chatbot

2021-03-03 21:50 UTC, dpalacios95 commented on custom_bot.py
> +        bot = initialize_bot()
bot = initialize_bot()
if not trained:
     train(bot)

2021-03-03 21:52 UTC, FrancoSecchi commented on custom_bot.py
> +        bot = initialize_bot()
El problema es el siguiente:
initialize_bot()
trained = True (Porque la base se crea a penas se inicializa el bot)
No entra al not trained
Nunca se entrena

2021-03-03 21:59 UTC, dpalacios95 commented on logs.py
👍

2021-03-03 22:00 UTC, dpalacios95 commented on custom_bot.py
> +                graph, instagram_api = facebook_credentials(), instagram_credentials()
Bueno pero separen las variables:
graph = facebook_credentials()
instagram_api = instagram_credentials()

2021-03-03 22:03 UTC, dpalacios95 commented on custom_bot.py
> +    return True
Entiendo que la función take_name en realidad permite el ingreso del nombre del usuario, ósea input_user_name() o ask_user_name , después lo guarda.
Por que no setean la variable is_taken_name = False , y en el caso de que el usuario ingrese su nombre y se guarde en el archivo de forma correcta la cambian a True

2021-03-03 22:06 UTC, FrancoSecchi commented on custom_bot.py
> +    return True
Esta hecho en el custom_bot

2021-03-03 23:20 UTC, dpalacios95 requested changes
Espectacular chicos! Muy buen laburo, un par de detalles y les tire algunas suggestions simples 😄

2021-03-03 23:20 UTC, dpalacios95 commented on custom_bot.py
> +    return True
```suggestion
```

2021-03-03 23:20 UTC, dpalacios95 commented on custom_bot.py
> +                is_taken_name = ask_name()
```suggestion
                ask_name()
                is_taken_name = True
```

2021-03-03 23:20 UTC, dpalacios95 commented on custom_bot.py
> +                facebook_api, instagram_api = connection_facebook_api(), connection_instagram_api()
```suggestion
                facebook_api = connection_facebook_api()
                instagram_api = connection_instagram_api()
```

2021-03-03 23:20 UTC, dpalacios95 commented on apis/facebook.py
> +from logs import (write_log, STATUS_FILE, get_credentials,
Cuidado get_credentials quedo en utils ahora

2021-03-03 23:20 UTC, dpalacios95 commented on apis/facebook.py
> +    while number not in range(len(list_)):
No se olviden que la función range va de `0 a longitud de lista - 1` entonces si yo ingreso el ultimo numero no lo seleccionaría porque cuenta el cero. Pruebenlo por las dudas :)

2021-03-03 23:20 UTC, dpalacios95 commented on apis/facebook.py
> +    while not found_file:
```suggestion
    path = os.path.abspath(input_user_chat("Enter the file path, the file must be .jpg: "))
    while not os.path.exists(path):
        print_write_chatbot(f"The path doesnt exists, please enter a correct path \n", color = "red",
                                 attrs_color = ["bold"])
        path = os.path.abspath(input_user_chat("Enter the file path, the file must be .jpg: "))
```

2021-03-03 23:20 UTC, dpalacios95 commented on apis/facebook.py
> +def if_text_in_info(info: dict, posts_id: list, count: int):
Yo meteria esta logica directo donde la usa, en este caso seria en post_related

2021-03-03 23:20 UTC, dpalacios95 commented on apis/facebook.py
>      try:
Verifiquen donde podrían fallar y de ultima si tienen que hacer varios try-except en distintas partes del código es válido siempre y cuando no están anidados 😛

2021-03-03 23:20 UTC, dpalacios95 commented on apis/facebook.py
>      try:
El bloque del try-except es muy grande, por eso digo

2021-03-03 23:20 UTC, dpalacios95 commented on apis/instagram.py
> +            is_following = True
```suggestion
    is_following = False
    if not is_own_feed(): # Hagan esta funcion is_own_feed() es super simple
        followed_users = get_follows(api, show=False)
        user_info = api.username_info(username)
        if user_info['user']['is_private']:
            for users in following['users']:
                if user_info['user']['pk'] in users.values():
                    is_following = True
        # no tiene else porque is_following ya esta seteado por default en False
    return is_following
```

2021-03-03 23:20 UTC, dpalacios95 commented on apis/instagram.py
> +    if attribute in comments_post.keys() and comments_post[attribute]:
```suggestion
    if comments_post.get(attribute):
```

2021-03-03 23:20 UTC, dpalacios95 commented on apis/instagram.py
> +        for comment in comments_post[attribute]:
```suggestion
        for comment_number, comment in enumerate(comments_post[attribute]):
```

2021-03-03 23:20 UTC, dpalacios95 commented on apis/instagram.py
> +        if type(post_data["caption"]) == dict:
```suggestion
        if isinstance(post_data["caption"], dict):
```

2021-03-03 23:20 UTC, dpalacios95 commented on apis/instagram.py
> +        if post_number < 0 or post_number >= max_number:
Arreglen esto es muy simple :)

2021-03-03 23:20 UTC, dpalacios95 commented on apis/instagram.py
> +        if not comments['comments'][comment_number]:
Same

2021-03-03 23:20 UTC, dpalacios95 commented on apis/instagram.py
>  # ------------ CONNECTIONS AND CREDENTIALS ---------------#
Estas funciones no son utils?

2021-03-03 23:20 UTC, dpalacios95 commented on logs.py
> +from utils.utils import get_current_username
CUIDADO con el import ciclico, basicamente es cuando un modulo A intenta importar cosas de un modulo B que importa al modulo A
Metan la funcion get_current_username aca si quieren 👍

2021-03-03 23:20 UTC, dpalacios95 commented on utils/utils.py
> +def get_current_username(first_time = False) -> str:
Manden esta funcion a logs para hacerlo mas facil :)

2021-03-04 00:12 UTC, FrancoSecchi commented on apis/facebook.py
>      try:
Seria mejor tener los try-except en las funciones de comment, like, etc..?

2021-03-04 22:06 UTC, merged